### ISSUE TITLE
Error: An API access token is required to use Mapbox GL. 

### ISSUE THREAD

**Issue by kusumakarb** [amancevice/caravel#11]
The "Mapbox" visualisation indicates that it is loading, but the console has the has the following error:

`explore.entry.js:34 Uncaught Error: An API access token is required to use Mapbox GL. See https://www.mapbox.com/developers/api/#access-tokens`

**Comment by amancevice** [comment]
Looking at https://github.com/airbnb/caravel/issues/707 it seems like you may need a `MAPBOX_API_KEY` value (which in turn requires signing up with MapBox). Have you tried setting this value via ENV variables or a custom `caravel_config.py` file? I don't have a MapBox acct so I cannot test.

**Comment by amancevice** [comment]
I confirmed this works with an API key. Here's what I did to get it working:
1. Signed up for MapBox and created an API Key
2. Started up a demo caravel instance with:

``` bash
docker run --name caravel -d -p 8088:8088 -e CARAVEL_MAPBOX_API_KEY=<key> amancevice/caravel
```
1. Load the caravel demo with:

``` bash
docker exec -it caravel demo
```
1. Confirmed the [MapBox slice](http://localhost:8088/caravel/explore/table/5/?since=2014-01-01&slice_id=26&all_columns_x=LON&all_columns=occupancy&until=2016-12-12&json=false&datasource_name=long_lat&mapbox_style=mapbox%3A%2F%2Fstyles%2Fmapbox%2Flight-v9&where=&datasource_type=table&viz_type=mapbox&datasource_id=7&granularity=day&all_columns_y=LAT&slice_name=Mapbox+Long%2FLat&row_limit=500000) works in the demo
